name: Build release

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Build on ${{matrix.os}}
    runs-on: ${{matrix.os}}
    permissions: 
      contents: write
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, windows-2025, macos-14]

    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE, so the job can access it
      - uses: actions/checkout@v4

      - name: Initialize MSVC environment
        uses: ilammy/msvc-dev-cmd@v1
        if: matrix.os == 'windows-2025'
        with:
          arch: x64

      - name: Make Script Files Executable
        shell: bash
        run: chmod +x scripts/setup-download.sh scripts/setup-runner.sh scripts/setup-cmake-configure.sh scripts/setup-ninja-compile.sh

      - name: Download SOFA, Plugins and Python
        shell: bash
        run: ./scripts/setup-download.sh

      - name: Setup Runner 
        shell: bash
        run: ./scripts/setup-runner.sh
        
      - name: Configure
        shell: bash
        run: ./scripts/setup-cmake-configure.sh build src plugins
        
      - name: Compile
        shell: bash
        run: ./scripts/setup-ninja-compile.sh build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: SOFA-Robotics_${{matrix.os}}
          path: build/SOFA*.zip
        
