name: Build release

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * *' # Runs every night at midnight

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
    GH_TOKEN: ${{ github.token }}

jobs:
  build:
    name: Build on ${{matrix.os}}
    runs-on: ${{matrix.os}}
    permissions: 
      contents: write
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, windows-2025, macos-14]

    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE, so the job can access it
      - uses: actions/checkout@v4

      - name: Initialize MSVC environment
        uses: ilammy/msvc-dev-cmd@v1
        if: matrix.os == 'windows-2025'
        with:
          arch: x64

      - name: Build SOFA-Robotics
        uses: ./
        with:
          os: ${{matrix.os}}

      - name: Get current date and time
        shell: bash
        run: echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
      
      - name: Create Release
        run: |
          echo "Uploading release for ${{matrix.os}}"
          gh release create release-${{ github.ref_name }} build/SOFA*.zip --clobber --title "SOFA-Robotics ${{ github.ref_name }}" --notes "Release for ${{ github.ref_name }}. Last updated on ${{ env.NOW }}." --repo SofaComplianceRobotics/SofaRobotics.CI --latest