name: Build release

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * *' # Runs every night at midnight

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
    GH_TOKEN: ${{ github.token }}

jobs:
  build:
    name: Build on ${{matrix.os}}
    runs-on: ${{matrix.os}}
    permissions: 
      contents: write
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, windows-2025, macos-15]

    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE, so the job can access it
      - uses: actions/checkout@v4

      - name: Initialize MSVC environment
        uses: ilammy/msvc-dev-cmd@v1
        if: matrix.os == 'windows-2025'
        with:
          arch: x64

      - name: Build SOFA-Robotics
        uses: ./
        with:
          os: ${{matrix.os}}
          sofa_version: main-unstable

  release:
    name: Create Release
    runs-on: ubuntu-22.04
    needs: build
    if: github.event_name != 'pull_request'
    permissions: 
      contents: write
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: SOFA-Robotics_*
          path: build
          merge-multiple: true

      - name: Get current date and time
        shell: bash
        run: echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
      
      - name: Create Release
        shell: bash
        env:
          RELEASE_TAG: release-${{ github.ref_name }}
          RELEASE_REPO: SofaComplianceRobotics/SofaRobotics.CI
        run: |
          echo "Uploading release ${RELEASE_TAG}"
          if gh release view "${RELEASE_TAG}" --repo "${RELEASE_REPO}" >/dev/null 2>&1; then
            gh release delete "${RELEASE_TAG}" --repo "${RELEASE_REPO}" --yes --cleanup-tag
          fi
          gh release create "${RELEASE_TAG}" build/SOFA*.zip \
            --title "SOFA-Robotics ${GITHUB_REF_NAME}" \
            --notes "Release for ${GITHUB_REF_NAME}. Last updated on ${NOW}." \
            --repo "${RELEASE_REPO}" \
            --latest